# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-04 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20190318_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_description',
            field=models.TextField(default='no offer', max_length=400),
        ),
    ]
