# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-07 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_offer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_description',
            field=models.TextField(max_length=400),
        ),
    ]
