# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-07 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20190407_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_description',
            field=models.TextField(default='No Offer', max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
